### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by zabullet** [vmware/vmware-go-kcl#1]
I'm surprised this isn't building, but I'm getting

# github.com/vmware/vmware-go-kcl/clientlibrary/worker
..\github.com\vmware\vmware-go-kcl\clientlibrary\worker\shard-consumer.go:186:40: cannot use retriedErrors (type int) as type float64 in argument to math.Exp2

> go version
go version go1.11.1 windows/amd64

zb.

**Comment by taojwmware** [comment]
Thanks for reporting the issue. It has been fixed:
https://github.com/vmware/vmware-go-kcl/commit/8bbffc3cc56c840d9047f01dc655129ed5432a11

Tao
