### ISSUE TITLE
Option to assume role in AWS Kinesis client

### ISSUE THREAD

**Issue by bscaka345** [vmware/vmware-go-kcl#101]
Is there a way to assume a role (role_arn) and pass it to a new worker? In the best case, I would like to read the role_arn from a config file and then assume the role in Go. Without the assumed role, my current program cannot find the stream under the account because it is not pointing to the account of a third-party.

**Comment by taojwmware** [comment]
Please check the AWS doc and it should work:
https://aws.amazon.com/blogs/architecture/field-notes-how-to-enable-cross-account-access-for-amazon-kinesis-data-streams-using-kinesis-client-library-2-x/
