### ISSUE TITLE
Workload skewed across workers

### ISSUE THREAD

**Issue by komealy** [vmware/vmware-go-kcl#109]
### Describe the bug

I have 20`vmware-go-kcl` based workers, with a sane amount of memory per each (12Gi). Processing data from the stream was able to catch up decently quickly, but the workload is extremely skewed. Some workers are working way overtime, and some are doing basically nothing. See this as an example of memory usage between them. That also “makes sense” because I see in the dynamo checkpoints table some pods are managing 14-16 shards, and some only 1-3…

How can I get this to run more equally between workers?

### Reproduction steps

1. Start with multiple kinesis shards, I had 160
2. Start multiple workers, I had 20
3. Use the monitoring tool of your choice to check metrics and see some workers processing much more records than others
  a. ![image](https://user-images.githubusercontent.com/3846175/231750582-0b3eb0df-57e1-471a-a576-77c690a26051.png)
4. Compare `AssignedTo` entries in the dynamo checkpoint table, and see that there are some workers that have many shards assigned to them, and some workers that have only a few.

### Expected behavior

Workers start and get assigned shards to work on.
When new assignments are made, the amount of shards each worker is working on stays at a comparable level, or even better as even as possible.
In my situation with 160 shards and 20 workers, each worker should manage exactly 8 shards.

**Comment by komealy** [comment]
It looks like this is mitigated somewhat with the `.WithLeaseStealing(true)` chained function when setting up your `config.NewKinesisClientLibConfig()`. It doesn't get to the point of "perfect" parity, but it does help somewhat. I was trying to avoid setting `.WithMaxLeasesForWorker(maxLeasesPerWorker)` because if the kinesis stream scales in-flight, that would have to be re-evaluated...

The current suggestion in another issue is to have a polling loop checking for the shard count, and possibly just exiting when it changes. That way the process will come back up in a container orchestration scenario with the new values, and work out anyway. I would like to see a solution that is a bit more graceful...

**Comment by taoj-action** [comment]
In your case, set WithMaxLeasesForWorker(8) to put a cap on the workload for workers.
https://github.com/vmware/vmware-go-kcl/blob/master/test/worker_test.go#L76

**Comment by komealy** [comment]
Yes, that is what I ended up doing. I understand that the behavior of this is meant to coincide with AWS's java version of the KCL, and it would act the same way and require me to use the same setting.

My original request probably would need to go to AWS to have them create a balanced mode that does this load balancing automatically without me needing to change settings and restart clients to apply those settings when some scaling happens.

I can live with restarting my clients whenever my kinesis stream OR my clients scale horizontally to redistribute the load. I just think it could be done more gracefully in runtime without as much interruption and restarting needed.
