### ISSUE TITLE
NewWorker Accept Checkpoint interface

### ISSUE THREAD

**Issue by mxu-splunk** [vmware/vmware-go-kcl#15]
The current NewWorker func automatically init the default Dynamo checkpoint. It would be more convenient if it accepts checkpoint interface as a input so that folks can inject customized checkpoint implementation. On the other hand, the checkpoint interface is defined to be private now. Any plan to add these supports so that people can implement their own checkpoint and inject to the worker?

**Comment by taojwmware** [comment]
Any implementation on checkpoint must ensure that the data will not lost when KCL enable app crashed. Yes, it is possible for using other implementation. I was even thinking about the possibility of abstracting Kinesis and let this library to handle Kafka in the future.

**Comment by jdavisclark** [comment]
this, as well as the kinesis abstraction, would be huge. I am actively looking to either fork this repo and port it to dynamo streams + custom checkpointing, or roll my own.

**Comment by taojwmware** [comment]
I have proposed a change: https://github.com/vmware/vmware-go-kcl/pull/17 for adding custom checkpoint implementation which doesn't break the current interface.

I will try to find a way to abstract the Kinesis and my immediate goal is to support Kafka.

**Comment by jdavisclark** [comment]
I'm going to be playing with it on my end as well, so I'd love to see what you come up with. My goal will be supporting dynamo streams, but anything that works for Kinesis should be easy to make a dynamo stream provider for.

**Comment by taojwmware** [comment]
The #17 is now in master. I am closing this issue. Please open a new one if any issue.
