### ISSUE TITLE
Lease release on shutdown

### ISSUE THREAD

**Issue by Sytten** [vmware/vmware-go-kcl#26]
When the worker terminates properly (via the Shutdown interface), it should release the lease it has in DynamoDB so other workers can pick it up. This is even more an issue since there is no lease stealing.

**Comment by taojwmware** [comment]
The lease renew interval is controlled by FailoverTimeMillis
https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/config/config.go#L197

and its default value set to 10secs.
https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/config/config.go#L58

User can control how soon the lease can expire using WithFailoverTimeMillis.
https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/config/kcl-config.go#L128 

This provides more flexibility than simply release the lease.

**Comment by taojwmware** [comment]
Here is an example on how to use it.
https://github.com/vmware/vmware-go-kcl/blob/master/test/worker_test.go#L59

**Comment by Sytten** [comment]
I am aware of this mechanism, but I still think it's a different feature. When a worker shuts down gracefully, it has a clear intention of not consuming records anymore. Thus it should release it's lease on the shard. A dirty/hard shutdown is where the FailoverTimeMillis is useful to prevent locking a shard forever.

I opened the ticket, because it seems especially important for cases where we might want a Higher FailoverTimeMillis (your test worker is 5m for example). If you deploy a lot with CD, this will become an issue really fast.

In fact, this might not be an issue if the update of the lease was an async operation instead of sync after the processing of the batch of records. I can see many use cases (including mine) where the processing of records can be slow sometimes and thus need a higher FailoverTimeMillis to prevent it from expiring while processing records.

**Comment by taojwmware** [comment]
Yes, it is possible we could add release lease after each of the following Shutdown
https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/worker/shard-consumer.go#L244
https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/worker/shard-consumer.go#L252

The issue of doing so is that user need to make sure to checkpoint before the Shutdown function returns. 
https://github.com/vmware/vmware-go-kcl/blob/master/test/worker_test.go#L259

**Comment by Sytten** [comment]
Is this because the lease update checks for `nil` when releasing it?

**Comment by taojwmware** [comment]
nil is for the end of shard which is the case for parent shard when splitting a shard. If someone put a go-routine into the callback function and forgot to checkpoint it or checkpoint it too late, the lease might be released already.

**Comment by taojwmware** [comment]
Actually, we did release the lease already using defer function and it is called when function returns. So, user has to be careful on this when doing checkpointing.
https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/worker/shard-consumer.go#L130

**Comment by Sytten** [comment]
That's weird because I have not seen this behavior with my tests.

**Comment by taojwmware** [comment]
This is the log message from test: See "Release lease for shard ..."

time="2019-07-08T16:21:53-05:00" level=debug msg="Received 0 records, MillisBehindLatest: 0"
time="2019-07-08T16:21:53-05:00" level=info msg="Worker shutdown in requested."
time="2019-07-08T16:21:53-05:00" level=info msg="Shutting down..."
time="2019-07-08T16:21:54-05:00" level=info msg="Release lease for shard shardId-000000000000"
time="2019-07-08T16:21:54-05:00" level=info msg="Shutting down cloudwatch metrics system..."
time="2019-07-08T16:21:54-05:00" level=info msg="Shutting down monitoring system"
time="2019-07-08T16:21:54-05:00" level=debug msg="Flushing metrics data. Stream: kcl-test, Worker: test-worker"
time="2019-07-08T16:21:54-05:00" level=info msg="Cloudwatch metrics system has been shutdown."
time="2019-07-08T16:21:54-05:00" level=info msg="Worker loop is complete. Exiting from worker."

**Comment by Sytten** [comment]
Yes, but when you take a look at the release method, its only a local release not a remote

**Comment by taojwmware** [comment]
got it. Thanks for finding this bug!

**Comment by taojwmware** [comment]
PR: https://github.com/vmware/vmware-go-kcl/pull/29 for the fix.

**Comment by taojwmware** [comment]
merged.

**Comment by Sytten** [comment]
@taojwmware Hum I found another problem with this new change (you should probably revert until fixed). Now on shutdown the whole record is removed including the last checkpoint! That means the next consumer will need to start from scratch!

**Comment by taojwmware** [comment]
The syncShard will rebuilt shard info periodically. 
https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/worker/worker.go#L232

**Comment by Sytten** [comment]
Yes if you don't kill the app before... Otherwise the information is lost. Just tested it and it's what is happening on my side on a graceful shutdown (it's probably why it was only updating the local cache in the first place).

**Comment by taojwmware** [comment]
Can you elaborate the scenario? If the app is killed, the other worker will rebuilt the info with nobody claims the shard. Then, it can claim the shard if max shard lease for worker isn't reached.

**Comment by taojwmware** [comment]
I see. The checkpointer info inside dynamoDB on the shard is gone. Will fix it.

**Comment by taojwmware** [comment]
The previous commit has been reverted. Here is the new change with both unit test and integration test updated.
https://github.com/vmware/vmware-go-kcl/pull/31

**Comment by Sytten** [comment]
Looking at the code, it seems fine to me. I will give it a try today! Thanks for the quick update

**Comment by taojwmware** [comment]
cool. I will wait for your test result before submitting it to master. Thanks!

**Comment by taojwmware** [comment]
#31 has been submitted.
