### ISSUE TITLE
Expose a logger interface

### ISSUE THREAD

**Issue by Sytten** [vmware/vmware-go-kcl#27]
Logging is not standard in golang, but forcing any logger on lib users is usually not considered good practice. It would be awesome if we could have an interface instead!

**Comment by taojwmware** [comment]
The only issue is golang log does not provide enough abstraction on common functionalities. 
https://golang.org/pkg/log/

We had a very long debate on which logging package to use and finally settled down to logrus. It is quite extensible and our internal codebase uses customized log library with compatible interface as logrus.

https://medium.com/@_orcaman/most-imported-golang-packages-some-insights-fb12915a07

**Comment by taojwmware** [comment]
The major advantage of using logrus is that it provides structured logger for Go. The logging result can be easily ingested into ElasticSearch for log analysis.
https://github.com/sirupsen/logrus

**Comment by Sytten** [comment]
Yeah I agree that the golang log is not good enough. We happen to use zap (which is also a structured logger). The problem is mainly that it is a bit painful (but doable with hooks) to redirect logs from logrus to zap. What I have seen libraries doing (like AWS SDK) is to create a custom logging interface (with a default if needed) that the users can then implement with their logger of choice.

**Comment by taojwmware** [comment]
zap is interesting. https://github.com/uber-go/zap I will take a look on this.

**Comment by Sytten** [comment]
I will write a logrus hook for that.

**Comment by Sytten** [comment]
I finally wrote the hook https://github.com/Sytten/logrus-zap-hook, though I think an interface would be better ;)

**Comment by taojwmware** [comment]
PR: https://github.com/vmware/vmware-go-kcl/pull/43 
for adding support on both logrus and zap logger.
