### ISSUE TITLE
AT_TIMESTAMP InitialPositionInStream does not work

### ISSUE THREAD

**Issue by chayan-g** [vmware/vmware-go-kcl#37]
```
// If there isn't any checkpoint for the shard, use the configuration value.
if shard.Checkpoint == "" {
  initPos := sc.kclConfig.InitialPositionInStream
  log.Debugf("No checkpoint recorded for shard: %v, starting with: %v", shard.ID,
    aws.StringValue(config.InitalPositionInStreamToShardIteratorType(initPos)))
  shardIterArgs := &kinesis.GetShardIteratorInput{
    ShardId:           &shard.ID,
    ShardIteratorType: config.InitalPositionInStreamToShardIteratorType(initPos),
    StreamName:        &sc.streamName,
  }
  iterResp, err := sc.kc.GetShardIterator(shardIterArgs)
  if err != nil {
    return nil, err
  }
  return iterResp.ShardIterator, nil
}
```

If no checkpoint is found and the InitialPositionInStream is `AT_TIMESTAMP`, `GetShardIteratorInput` should take the `Timestamp` argument, which in the above code snippet (from _ /clientlibrary/worker/shard-consumer.go_) is missing.

As a result when I use the library with the AT_TIMESTAMP config, I get the following error:

`InvalidArgumentException: Must specify timestampInMillis parameter for iterator of type AT_TIMESTAMP. Current request has no timestamp parameter.\n\tstatus code: 400,`

**Comment by taojwmware** [comment]
Have you tried?

	kclConfig := cfg.NewKinesisClientLibConfig("appName", streamName, regionName, workerID).
		WithTimestampAtInitialPositionInStream(tm).

func (c *KinesisClientLibConfiguration) WithTimestampAtInitialPositionInStream(timestamp *time.Time) *KinesisClientLibConfiguration {
	c.InitialPositionInStream = AT_TIMESTAMP
	c.InitialPositionInStreamExtended = *newInitialPositionAtTimestamp(timestamp)
	return c
}

**Comment by chayan-g** [comment]
Yes of course I tried that. I shared the code snippet from _shard-consumer.go_ library file which shows that it completely ignores the timestamp configuration.
