### ISSUE TITLE
metrics: GetRecords time includes ProcessRecords time

### ISSUE THREAD

**Issue by arl** [vmware/vmware-go-kcl#51]
Context: 
In my use of KCL, I'm controlling the read throuput at shard level by performing a `time.Sleep` at the top of `myrecordProcessor.ProcessRecords`. This allows to not exceed the aws data limits described [here](https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html).

By looking at the GetRecords and ProcessRecords on my metrics dashboard I was expecting to see the `process_records_time` metrics more or less equal to the sleep duration. That is the case.

What I didn't expect though was to see the `get_records_time` match the same value.

Looking at the code, I was excepting to have `get_records_time` be the time taken to run that code block:

https://github.com/vmware/vmware-go-kcl/blob/10dd997fddcc5decfeadfed614b5d9dab175d3ff/clientlibrary/worker/shard-consumer.go#L194-L208

Instead `getRecordsTime := time.Since(getRecordsStartTime) / 1000000` is computed after both calls to `GetRecords` and `ProcessRecords`.
Am I missing something here? Is this the expected behavior?

If not I can propose a PR for that.

**Comment by taojwmware** [comment]
Yes, it is a bug. Thanks for reporting this.
