### ISSUE TITLE
Use time.Duration instead of milliseconds count

### ISSUE THREAD

**Issue by arl** [vmware/vmware-go-kcl#52]
Many, if not all, time duration in whole the code base are expressed in milliseconds. In Go `time.Duration` expressly exists for this and makes it easier to read, manipulate and use in coordination with other libraries.

I propose to use `time.Duration` everywhere, even in the `metrics.MonitoringService` interface. That would be a breaking change though so it would require a new major tag.

**Comment by taojwmware** [comment]
Using milliseconds inline with original Amazon's KCL, I don't think it worthwhile to do so. Especially, this will be a breaking change. We'd rather write a conversion utility instead.

**Comment by arl** [comment]
Ok, makes sense.
