### ISSUE TITLE
Error in publishing cloudwatch metrics

### ISSUE THREAD

**Issue by uizu** [vmware/vmware-go-kcl#54]
It seems the input params are not used to set monitor service in cloudwatch Init function. 
The empty appName, streamName and workerID cause PutMetricData failed with error string "Error in publishing cloudwatch metrics. Error: InvalidParameter...". 
Could you help to check this issue? Thanks.

**Comment by taojwmware** [comment]
Thanks for reporting this bug. It has been fixed in the latest commit.
