### ISSUE TITLE
Add go mod support and release.

### ISSUE THREAD

**Issue by h7kanna** [vmware/vmware-go-kcl#6]
Hi, 
I am thinking of trying this package. Can the team let me know if this package is production ready?
Also if possible add go mod support.

Thanks,

**Comment by taojwmware** [comment]
Yes, this package has been used in production for a few projects. We will add go mod support soon but it requires upgrading to golang 1.11.

**Comment by taojwmware** [comment]
The go mod support has been just released. 5a1624c5820b3a05378c0d3f09642ff808c8eaa3
