### ISSUE TITLE
Too many calls to DescribeStream

### ISSUE THREAD

**Issue by arl** [vmware/vmware-go-kcl#61]
We recently faced a problem on our production cluster consuming a high-volume kinesis stream.
2 different services are consuming that stream. Each service is made of multiple workers.
One service is based off java KCL while the other one, ours, uses this library.

Both services saw an increase in `LimitExceededException` errors on the DescribeStream api call.

```
Error in DescribeStream: streamAAA Error: LimitExceededException: Rate exceeded for stream streamAAA under account BBBB.
	status code: 400, request id: xxxxx Request: {
  StreamName: "streamAAA"
}
```

The thing is there's a 10 api call per second hard limit imposed by AWS.

My understanding of the problem is the following:

Both services had been running for 2 weeks without problems but for some reason. At one moment though, planets were aligned so that nearly all calls to `DescribeStream` were performed around the same time, actually exceeding the 10 calls per second hard-limit.

We got a response directly from AWS support about that:
```
Unfortunately, the limit of 10 trasactions per second for 'Describestream' API call is a hard limit and cannot be increased. However, there are workarounds for the 'Describestream' API call.
1. You can use the APIs ListShards and DescribeStreamSummary together as the combination of these two APIs will give all the information given by the DescribeStream API.
Reference: ListShards: ://docs.aws.amazon.com/kinehttpssis/latest/APIReference/API_ListShards.html
2. If the above workaround does not match your use case, please implement an exponential backoff mechanism where you catch the LimitExceededException and retry the request or use a cache to decrease the number of calls to DescribeStream API.
Reference: 
A. Reference: Error Retries and Exponential Backoff in AWS: https://docs.aws.amazon.com/general/latest/gr/api-retries.html
B. DescribeStreamSummary: https://docs.aws.amazon.com/kinesis/latest/APIReference/API_DescribeStreamSummary.html
3. If you are making Describe Stream API call quite frequently, try modifying the application by making a call to describe stream, save it in some cache to reduce the frequency of API calls.
```

I think the 2 solution (exponential back-off on DescribeStream failure) as already implemented in https://github.com/vmware/vmware-go-kcl/blob/d0e9c4cddbb74928972dc4ac0869ccf605720cb3/clientlibrary/worker/shard-consumer.go#L198-L203 could be a good solution. Eventually the sleep duration could also be randomized a bit in order to spread calls across seconds even more.

Would an addition of such feature to vmware-go-kcl be acceptable?

**Comment by taojwmware** [comment]
Yes, some random jitters can be added here to ensure w.syncShard() is not called very close.
https://github.com/vmware/vmware-go-kcl/blob/d0e9c4cddbb74928972dc4ac0869ccf605720cb3/clientlibrary/worker/worker.go#L305

**Comment by arl** [comment]
I'm gonna propose a PR for that tomorrow.
Random jitter or exponential backoff or both? What do you think would be preferable?
It should be optional, right?

**Comment by taojwmware** [comment]
I think random jitter should be good enough because w.syncShard() is called inside a loop.
https://github.com/vmware/vmware-go-kcl/blob/d0e9c4cddbb74928972dc4ac0869ccf605720cb3/clientlibrary/worker/worker.go#L235

Also, the default value for ShardSyncIntervalMillis is 1 minute already.
