### ISSUE TITLE
Create close channel first inside initialize method

### ISSUE THREAD

**Issue by scirlig-ellation** [vmware/vmware-go-kcl#67]
## Background

When we start the worker by calling the `Start` method, the application may fail due to AWS access rights or any AWS error, in that case we retry calling start couple of times. If retrying a certain amount of times is unsuccessful we handle the error and exit our program.

However we also have a signal listener which shuts down the application gracefully, and also calls `Shutdown` method. Considering our workers always failed to start due to failed `initialize`
When the `Shutdown` method inside the library is called, it attempts to close `stop` channel which was not yet created:

*worker.go#L134*
```go
close(*w.stop)
```

## Solution

I suggest to create the `stop` channel & and `waitGroup` in the first place when calling `initialize method` to avoid panics when calling the `Shutdown` method

Here's a small example of how our `Start` looks like:

##### Start

```go
var retries int
err := w.Start()
for err != nil && retries < app.config.Workers.MaxRetries {
	app.logger.Error(err)
	time.Sleep(5 * time.Second)
	err = w.Start()
	retries++
}
errChan <- err
```

**Comment by taojwmware** [comment]
We can do this by adding nil check at:
https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/worker/worker.go#L139
```
	if w.done || w.stop == nil {
		return
	}
```
