### ISSUE TITLE
(Still) Too many calls to DescribeStream

### ISSUE THREAD

**Issue by jmcclell** [vmware/vmware-go-kcl#69]
I don't believe you guys should consider #61 closed. `DescribeStream` is simply the wrong thing to use here. This is directly against AWS recommendations. That call has a hard limit for a reason.

The response @arl received from AWS mirrors the one my team received.

> You can use the APIs ListShards and DescribeStreamSummary together as the combination of these two APIs will give all the information given by the DescribeStream API. 
> Reference: ListShards: ://docs.aws.amazon.com/kinehttpssis/latest/APIReference/API_ListShards.html

Our particular setup is dealing with billions of stream events daily and our individual consumer process count is high. No amount of jitter is going to keep my team from throttling hard on this call and I suspect we're not in a unique position.

Our dev team is looking at patching this internally and we'll attempt to PR when we do, but any insight from the maintainers may be helpful. Having looked at the code, I can see what information is required but I can't get a sense for the cadence/frequency that each piece (stream status, shard list, etc.) is required. The `ListShards`  api has a high rate limit, but even the `DescribeStreamSummary` api is still capped at 20 per second. So, it may be that this library would be better served requesting each separately at different frequencies if possible.

**Comment by arl** [comment]
I second this. The solution implemented just slightly postponed the problem. In fact weeks after we experienced the same problem again. However due to a lack of bandwidth, I haven't been able to get back at this but I agree, a more robust solution is needed since this greatly limits the number of shards x consumers a stream can have, which defeats the purpose of Kinesis.
I haven't had a look at the KCL Java code, I'm wondering how it's done there

**Comment by jmcclell** [comment]
If you check the documentation for the `ListShards` API, it explicitly states they added it specifically for the KCL library. I found that interesting - clearly, they ran into a similar issue, but they were able to address it by adding to the Kinesis API. I'd be interested in what specific calls and the frequency of each the Java library makes, as well.

**Comment by taojwmware** [comment]
I have taken a look the proposed change at: 
https://github.com/discovery-digital/vmware-go-kcl/pull/1/files

It looks good. Please bring over the change here. Thanks for finding the issue!
