### ISSUE TITLE
Error in getRecords leaves a dangling record processor.

### ISSUE THREAD

**Issue by gi-el** [vmware/vmware-go-kcl#71]
If the AWS API call `GetRecords` fails in https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/worker/shard-consumer.go#L207 (e.g., with a 500 which happens once in a while), the lease is released (by https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/worker/shard-consumer.go#L142) and `getRecords` returns. Besides printing an error, nothing else happens in the caller (https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/worker/worker.go#L309).

Now, after the wait period, the main loop finds a shard with no lease and gets the lease, starting a new `ShardConsumer`, which creates a new `RecordProcessor` and calls `Initialize` on it. However, nobody has called `Shutdown` on the old one. 

The `RecordProcessorFactory` can't return the existing processor as it doesn't know the `ShardID` yet, so we're left with a processor that isn't properly terminated.

**Comment by taojwmware** [comment]
Each processor runs in its own go routine. The shutdown for record processor is used to give user a chance to checkpoint data. When GetRecords fails, the data hasn't been read yet and there is nothing to checkpoint. Each record processor runs in different go routine and it gets terminated once return.

It is not a bug.
