### ISSUE TITLE
Semantic versioning friendly version tags

### ISSUE THREAD

**Issue by arl** [vmware/vmware-go-kcl#74]
Don't know if this made on purpose or not, but I noted that the tag for version `1.0` version does not respect the format required for semantic versioning.
For instance `v-1.0` should be `v1.0.0` if the goal is to indicates the first major version (no dash and 3 numbers).
If you look at the [official Go package documentation website for vmware-go-kcl](https://pkg.go.dev/github.com/vmware/vmware-go-kcl@v0.0.0-20200310160057-7d5bfbb7a17b), indeed it shows no version for this project.
Now it is still possible to use this project with Go modules since `go mod` will use commits numbers, but IMHO you lose a lot of useful feature provided when respecting semantic versioning.

**Comment by taojwmware** [comment]
Fixed.
https://github.com/vmware/vmware-go-kcl/tree/v1.0.0
Thanks for pointing it out.
