### ISSUE TITLE
Prometheus metrics should add appname as label and not in the metric name

### ISSUE THREAD

**Issue by jregovic** [vmware/vmware-go-kcl#79]
The prometheus metrics package creates metrics names by prepending the appname to the metric name.

This cause the metrics service to fail if the app name has characters that are invalid for prometheus. Additionally, embedding the app name into the metric name makes queries difficult in cases where multiple, related consumer applications are running.

It would make more sens to add the app name  as a label and avoid the potential errors and better organize the data.

This:
`
	p.processedBytes = prom.NewCounterVec(prom.CounterOpts{
		Name: p.namespace + `_processed_bytes`,
		Help: "Number of bytes processed",
	}, []string{"kinesisStream", "shard"})`

May be better off as:
`p.processedBytes = prom.NewCounterVec(prom.CounterOpts{
		Name: `kcl_processed_bytes`,
		Help: "Number of bytes processed",
	}, []string{"kinesisStream", "shard","app"})`

With the app name added as a label:
`func (p *MonitoringService) IncrBytesProcessed(shard string, count int64) {
	p.processedBytes.With(prom.Labels{"shard": shard, "kinesisStream": p.streamName","app":p.appname}).Add(float64(count))
}`

**Comment by taojwmware** [comment]
Per [Prometheus metric and label naming](https://prometheus.io/docs/practices/naming/),  "A metric name should have a (single-word) application prefix relevant to the domain the metric belongs to. The prefix is sometimes referred to as namespace by client libraries. For metrics specific to an application, the prefix is usually the application name itself." The same applies to [cloud watch namespaces](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Namespac).

vmware-go-kcl even allows injecting a [custom metrics system](https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/metrics/interfaces.go), see an [example](https://github.com/vmware/vmware-go-kcl/blob/master/test/worker_test.go#L179).  This is especially useful for services that already use Prometheus and want to onboard KCL.
