### ISSUE TITLE
Possibility to Work w/ DynamoDB Streams 

### ISSUE THREAD

**Issue by zzhangsg** [vmware/vmware-go-kcl#80]
Hi,

I have a question regarding the usage, do we have a way to process data from DynamoDB Streams, like what is mentioned in https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.KCLAdapter.html, with the help of this library? From what I have researched, it looks like we would need an equivalent Go library for Kinesis Adapter so that then we can work with DynamoDB Streams. Anyway I still would like to post this question to get more ideas.

Thanks,
Zhen

**Comment by zzhangsg** [comment]
@taojwmware Hi, could you please kindly help with this issue? Appreciate it!

**Comment by taojwmware** [comment]
Even though DynamoDB stream API is similar to Kinesis data stream, they are not exactly the same and that's the reason why DynamoDB streams Kinesis Adapter comes in. Considering the fact that Kinesis is released before DynamoDB stream, I would challenge why AWS doesn't use Kinesis directly. 

Luckly, AWS just released a feature to directly [capture item-level change in DynamoDB tables into Kinesis data streams](https://aws.amazon.com/about-aws/whats-new/2020/11/now-you-can-use-amazon-kinesis-data-streams-to-capture-item-level-changes-in-your-amazon-dynamodb-table/) which makes the current feature request obsolete.

From AWS console, select the target dynamodb table and click **Manage streaming to Kineiss** button to select a Kinesis data stream for capturing the change event. Then, KCL can be used to consume the stream directly.
<img width="2263" alt="Screen Shot 2020-12-17 at 7 55 14 PM" src="https://user-images.githubusercontent.com/25186652/102565744-b1b1d280-40a3-11eb-8fd4-a447db37127c.png">

**Comment by ravikiran-zoman** [comment]
As per the aws dynamodb stream documentation ordering of item updates and exactly once feature which are provided by the dynamodb streams will be lost if we go with kinesis data streams. 
Is there any way to achieve the above features using this library with kinesis data streams enabled for a dynamodb ?
