### ISSUE TITLE
Error in publishing cloudwatch metrics. Error: NoCredentialProviders: no valid providers in chain.

### ISSUE THREAD

**Issue by pradeepkusingh** [vmware/vmware-go-kcl#88]
Seeing this error while using consumer.

**Comment by taojwmware** [comment]
This should be a setup issue. Make sure the instance profile has permission for couldwatch metric publishing. 

Or, take a look on the example, there isn't much configuration needed.
https://github.com/vmware/vmware-go-kcl/blob/master/test/worker_test.go#L70

Please follow the AWS document on how to configure credential.
https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html
