### ISSUE TITLE
How to use record deaggregator?

### ISSUE THREAD

**Issue by pradeepkusingh** [vmware/vmware-go-kcl#89]
How to use record deaggregator?

**Comment by pradeepkusingh** [comment]
I am using KPL and posting data to kinesis stream. but when I received data  using vmware KCL libraries, I don't see it is deaggregated. it comes as a multiple appending strings. I was expecting separate record of each string and should not be a singel string with my many json appending to a single string.

**Comment by taojwmware** [comment]
vmware go kcl just adds one line of de-agg from Kinesis-aggregation.
https://github.com/vmware/vmware-go-kcl/blob/master/clientlibrary/worker/shard-consumer.go#L212

Please try to use it to see the result. If not, please include your records in the issue for further investigation.
