### ISSUE TITLE
AWS Go SDK V2

### ISSUE THREAD

**Issue by errorhandler** [vmware/vmware-go-kcl#99]
Now that the AWS Go SDK V2 is [GA](https://aws.amazon.com/blogs/developer/aws-sdk-for-go-version-2-general-availability/) is there any plans to support V2 (via a new major version or the like)?

**Comment by fafg** [comment]
Hi @taojwmware I have a first version over here: https://github.com/fafg/vmware-go-kcl

there are some points open I would like to talk with you to understand a better strategy to follow:
1. some breaking changes (from the library side, not so much breaking changes)
   a) we could create a new repo to support SDK-v2 and so on, as AWS did to their repo. 
   b) create a new version with git tag and freeze v1
   c) if you decide to move to a new repo, I would have more suggestions regarding logging and metrics, I would like to move the implementations of each one in different modules (same repo) to be used during the configuration time, this way after the library user can decide to have one of the default implementations instead to have all of them inside of the library which it can increase the binary size with the extra dependencies it will not be used.
2. usage of context, now most API calls need context.
3. the dynamodb-chekcpointer_test.go has a mock to an interface which there isn't any more or at least as it would be in the previous sdkv1
   a) I would suggest here creating a new interface to keep things internally as it is. (these tests now are broken and need to be fixed)

so far the initial tests worked properly using worker_test.go and my AWS environment.

after we align I would open the PR.

in advance, I would like to say thank you for all your attention.

[]s

Fabiano

**Comment by taojwmware** [comment]
@fafg Thanks a lot for working on this! I think creating a new repo is the right approach. Yes, we could improve the folder structure as well to make it in line with the common go project structure. We can also use makefile instead of hmake. 

I will work on creating the new repo, see vmware-go-kcl-v2.

**Comment by fafg** [comment]
cool, I also like this approach. I will fork it as soon as you have it.

**Comment by fafg** [comment]
hi, @taojwmware I have moved from hypermake to makefile and added some ci pipeline, some extras to local scans like sonarqube locally.

![image](https://user-images.githubusercontent.com/9274235/141391307-68d91b69-69fb-4401-a84f-6298062b29a4.png)

![image](https://user-images.githubusercontent.com/9274235/141391411-261269bc-f256-4916-94c4-28dcebec7a24.png)

![image](https://user-images.githubusercontent.com/9274235/141391503-d179ecbd-667d-4dd8-a1b8-1bc3634b9977.png)

**Comment by taojwmware** [comment]
The request for creating new vmware-go-kcl-v2 repo has been approved and it will be available shortly. Thanks!

**Comment by tbhat05** [comment]
great progess @fafg

**Comment by fafg** [comment]
Thank you @tbhat05

**Comment by taojwmware** [comment]
Repo https://github.com/vmware/vmware-go-kcl-v2 has been created. It is currently a private repo, and I am working with our open-source team to make it public. Thanks and happy holidays!

**Comment by fafg** [comment]
yay nice news @taojwmware, thanks for letting us know \o/
you can check the changes I have done so far over here: https://github.com/fafg/vmware-go-kcl

happy new year for you all

**Comment by taojwmware** [comment]
@fafg https://github.com/vmware/vmware-go-kcl-v2 is now a public repo. I have cloned all your changes and put them into the new repo. Then, I updated the import path and fixed unit tests. There are still a few things that need to be done:
- Need to use credential chain (like v1) instead of static credentials because most deployments will use ec2 instance profile, kube2iam, or KIAM to get credentials. 
- Need to make sure integration tests are able to run against the real AWS resources, such as Kinesis stream, DynamoDB, etc.

Thanks!

**Comment by fafg** [comment]
Did you get the commits from upgrade/aws-sdk-v2 branch? the credentials are already fixed in that branch, I also noticed that... let me see If i can update something else.

thank you very much @taojwmware

**Comment by fafg** [comment]
seems we have finished the first steps, I will push now my usages to our stage environment, let you know when it's in prod.

thank you again @taojwmware 👍

**Comment by taojwmware** [comment]
Close this issue now. Please open any issue against vmware-go-kcl-v2 at
https://github.com/vmware/vmware-go-kcl-v2/issues
